['Google', 'Procter & Gamble', 'Merck', 'JPMorgan Chase', 'Walmart', 'Boeing', 'Procter_&_Gamble', 'INTC', 'JPMorgan_Chase', 'Apple']
Traceback (most recent call last):
  File "newsfrequencycount.py", line 93, in <module>
    articlelinecount = len(corpusReader.sents())
  File "/usr/local/lib/python2.7/dist-packages/nltk/corpus/reader/util.py", line 233, in __len__
    for tok in self.iterate_from(self._toknum[-1]): pass
  File "/usr/local/lib/python2.7/dist-packages/nltk/corpus/reader/util.py", line 291, in iterate_from
    tokens = self.read_block(self._stream)
  File "/usr/local/lib/python2.7/dist-packages/nltk/corpus/reader/plaintext.py", line 129, in _read_sent_block
    for sent in self._sent_tokenizer.tokenize(para)])
  File "/usr/local/lib/python2.7/dist-packages/nltk/data.py", line 949, in __getattr__
    self.__load()
  File "/usr/local/lib/python2.7/dist-packages/nltk/data.py", line 941, in __load
    resource = load(self._path)
  File "/usr/local/lib/python2.7/dist-packages/nltk/data.py", line 801, in load
    opened_resource = _open(resource_url)
  File "/usr/local/lib/python2.7/dist-packages/nltk/data.py", line 919, in _open
    return find(path_, path + ['']).open()
  File "/usr/local/lib/python2.7/dist-packages/nltk/data.py", line 641, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource u'tokenizers/punkt/english.pickle' not found.  Please
  use the NLTK Downloader to obtain the resource:  >>>
  nltk.download()
  Searched in:
    - '/home/sannamadan/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - u''
**********************************************************************
python: can't open file 'ne': [Errno 2] No such file or directory
python: can't open file 'newsfrequency.py': [Errno 2] No such file or directory
python: can't open file 'ne': [Errno 2] No such file or directory
usage: newsfrequencycount.py [-h] company
newsfrequencycount.py: error: too few arguments
4
['Walmart']
Traceback (most recent call last):
  File "newsfrequencycount.py", line 104, in <module>
    articlelinecount = len(corpusReader.sents())
  File "/usr/local/lib/python2.7/dist-packages/nltk/corpus/reader/util.py", line 233, in __len__
    for tok in self.iterate_from(self._toknum[-1]): pass
  File "/usr/local/lib/python2.7/dist-packages/nltk/corpus/reader/util.py", line 336, in iterate_from
    assert self._len is not None
AssertionError
1
['Procter & Gamble']
3
['JPMorgan Chase']
6
['Procter_&_Gamble']
Traceback (most recent call last):
  File "newsfrequencycount.py", line 104, in <module>
    articlelinecount = len(corpusReader.sents())
  File "/usr/local/lib/python2.7/dist-packages/nltk/corpus/reader/util.py", line 233, in __len__
    for tok in self.iterate_from(self._toknum[-1]): pass
  File "/usr/local/lib/python2.7/dist-packages/nltk/corpus/reader/util.py", line 336, in iterate_from
    assert self._len is not None
AssertionError
2
['Merck']
5
['Boeing']
7
['INTC']
python: can't open file 'ne': [Errno 2] No such file or directory
Procter_
Traceback (most recent call last):
  File "newsfrequencycount.py", line 95, in <module>
    for filename in os.listdir('../News/ArticlesData/' + company_name):
OSError: [Errno 2] No such file or directory: '../News/ArticlesData/Procter_'
Procter_
Traceback (most recent call last):
  File "newsfrequencycount.py", line 95, in <module>
    for filename in os.listdir('../News/ArticlesData/' + company_name):
OSError: [Errno 2] No such file or directory: '../News/ArticlesData/Procter_'
Procter_&_Gamble
Traceback (most recent call last):
  File "newsfrequencycount.py", line 104, in <module>
    articlelinecount = len(corpusReader.sents())
  File "/usr/local/lib/python2.7/dist-packages/nltk/corpus/reader/util.py", line 233, in __len__
    for tok in self.iterate_from(self._toknum[-1]): pass
  File "/usr/local/lib/python2.7/dist-packages/nltk/corpus/reader/util.py", line 336, in iterate_from
    assert self._len is not None
AssertionError
JPMorgan_Chase
Apple
